<?php return array(
    'root' => array(
        'name' => 'magicoli/wrap',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '3bb011254295c9995fe66f960b12fa0755b13fac',
        'type' => 'wordpress-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'czproject/git-php' => array(
            'pretty_version' => 'v4.3.0',
            'version' => '4.3.0.0',
            'reference' => 'f7fe85cc526c5f8e7ed809f7f9c68f2696940a8a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../czproject/git-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'erusev/parsedown' => array(
            'pretty_version' => '1.7.4',
            'version' => '1.7.4.0',
            'reference' => 'cb17b6477dfff935958ba01325f2e8a2bfa6dab3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../erusev/parsedown',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'magicoli/wrap' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '3bb011254295c9995fe66f960b12fa0755b13fac',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
