<?php return array(
    'root' => array(
        'name' => 'magicoli/osprojects',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '2fb1262501a2f767ed5eb4d1ee51f991f31a929b',
        'type' => 'wordpress-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'czproject/git-php' => array(
            'pretty_version' => 'v4.5.0',
            'version' => '4.5.0.0',
            'reference' => '3ea910e188849d5e239d65167010c05196310915',
            'type' => 'library',
            'install_path' => __DIR__ . '/../czproject/git-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'erusev/parsedown' => array(
            'pretty_version' => '1.7.4',
            'version' => '1.7.4.0',
            'reference' => 'cb17b6477dfff935958ba01325f2e8a2bfa6dab3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../erusev/parsedown',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'magicoli/osprojects' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '2fb1262501a2f767ed5eb4d1ee51f991f31a929b',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
